name: C/C++ CI

on:
  push:
    branches: [ main, add_ci_build_test ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodule_update: ON
        ref: ${{ github.ref }}
    - name: Build project
      run: echo "test"
      #    - name: configure
      #      run: ./configure
      #    - name: make
      #      run: make
      #    - name: make check
      #      run: make check
      #    - name: make distcheck
      #      run: make distcheck
      #
